In [1]:
inputs = [1.2, 5.1, 2.1]
weights = [3.1, 2.1, 8.7]
bias = 3.0

In [2]:
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias

In [3]:
print(output)

35.7


In [4]:
X = [0,0,1,1]
Y = [0,1,0,1]
W = [1,1]
bias = -1
Out1=X[0]*W[0]+ Y[0]*W[1]+ bias
if Out1>0:
    print(1)
else:
    print(0)
Out2=X[1]*W[0]+ Y[1]*W[1]+ bias
if Out2>0:
    print(1)
else:
    print(0)
Out3=X[2]*W[0]+ Y[2]*W[1]+ bias
if Out3>0:
    print(1)
else:
    print(0)
Out4=X[3]*W[0]+ Y[3]*W[1]+ bias
if Out4>0:
    print(1)
else:
    print(0)

0
0
0
1


In [5]:
inputs = [1.0, 2.0, 3.0, 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2.0
bias2 = 3.0
bias3 = 0.5

In [6]:
output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]
print(output)

[4.8, 1.21, 2.385]


In [7]:
import numpy as np 

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

In [8]:
output = np.dot(weights, inputs) + biases
print(output)

[4.8   1.21  2.385]


In [9]:
import math

X = [0.7, 0.1, 0.2]
target_output = [1, 0, 0]

loss = -(math.log(X[0]) * target_output[0] +
         math.log(X[1]) * target_output[1] +
         math.log(X[2]) * target_output[2])

print(loss)

print(-math.log(0.7))
print(-math.log(0.5))

0.35667494393873245
0.35667494393873245
0.6931471805599453


In [10]:
import numpy as np 

np.random.seed(0)

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

In [11]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [12]:
layer1 = Layer_Dense(4,5)

In [13]:
layer2 = Layer_Dense(5,2)

In [14]:
layer1.forward(X)
print(layer1.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]


In [15]:
layer2.forward(layer1.output)

In [16]:
import numpy as np 
!pip install nnfs
import nnfs
from nnfs.datasets import spiral_data  

nnfs.init()

X, y = spiral_data(100, 3)   

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [17]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


In [18]:
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

In [19]:
layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()

layer1.forward(X)

#print(layer1.output)
activation1.forward(layer1.output)
print(activation1.output)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-02
  0.00000000e+00]]


In [20]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()


In [21]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [22]:
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities


In [23]:

X, y = spiral_data(samples=100, classes=3)

X

array([[ 0.00000000e+00,  0.00000000e+00],
       [ 2.99555692e-03,  9.64660756e-03],
       [ 1.28809698e-02,  1.55628482e-02],
       [ 2.99747903e-02,  4.44809627e-03],
       [ 3.93124595e-02,  9.32828337e-03],
       [ 8.28829070e-04,  5.04982509e-02],
       [ 5.34835160e-02,  2.85062827e-02],
       [ 4.17361967e-02,  5.70752136e-02],
       [ 5.54633923e-02,  5.87686822e-02],
       [ 8.16038325e-02,  4.00659069e-02],
       [ 8.91875103e-02,  4.74197045e-02],
       [ 1.07160836e-01, -2.93638241e-02],
       [ 1.21183202e-01, -2.64751446e-03],
       [ 1.28777727e-01,  2.56794747e-02],
       [ 1.41112968e-01, -9.22449492e-03],
       [ 1.50579467e-01, -1.68126337e-02],
       [ 1.13476366e-01, -1.15077794e-01],
       [ 1.71552509e-01, -7.51816481e-03],
       [ 1.67186841e-01, -7.14591444e-02],
       [ 1.91325873e-01,  1.50793232e-02],
       [ 1.36771902e-01,  1.48679554e-01],
       [ 1.35606423e-01, -1.63114399e-01],
       [ 1.04024746e-01, -1.96370989e-01],
       [ 2.

In [24]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], d

In [25]:
dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

In [26]:
dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

In [27]:
dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]


In [28]:
import numpy as np 
import nnfs
from nnfs.datasets import spiral_data


nnfs.init()

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

class Loss_CategoricalCrossentropy(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)

        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]

        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped*y_true, axis=1)

        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods




X, y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

loss_function = Loss_CategoricalCrossentropy()
loss = loss_function.calculate(activation2.output, y)

print("Loss:", loss)

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
Loss: 1.0986104


In [29]:
import numpy as np

In [30]:
X = np.array([ [ 0, 0, 1 ],
               [ 0, 1, 1 ],
               [ 1, 0, 1 ],
               [ 1, 1, 1 ] ])
print(X)


[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [31]:
y = np.array([[0,0,1,1]]).T
print(y)

[[0]
 [0]
 [1]
 [1]]


In [32]:
n_inputs = 3
n_outputs = 1
#Wo = 2 * np.random.random( (n_inputs, n_outputs) ) - 1
Wo = np.random.random( (n_inputs, n_outputs) ) * np.sqrt(2.0/n_inputs)
print(Wo)

[[0.0127423 ]
 [0.35011024]
 [0.05558225]]


In [33]:
def sigmoid(z):
    """The sigmoid activation function."""
    return 1 / (1 + np.exp(-z))

In [34]:
def relu(z):
    """The ReLU activation function."""
    return max(0, z)

In [35]:
def sigmoid_prime(z):
    """The derivative of sigmoid for z."""
    return z * (1 - z)

In [36]:
for n in range(10000):
    # forward propagation
    l1 = sigmoid(np.dot(X, Wo))
    
    # compute the loss
    l1_error = y - l1
    #print("l1_error:\n", l1_error)
    
    # multiply the loss by the slope of the sigmoid at l1
    l1_delta = l1_error * sigmoid_prime(l1)
    #print("l1_delta:\n", l1_delta)
    
    #print("error:", l1_error, "\nderivative:", sigmoid(l1, True), "\ndelta:", l1_delta, "\n", "-"*10, "\n")
    # update weights
    Wo += np.dot(X.T, l1_delta)

print("l1:\n", l1)

l1:
 [[0.00966773]
 [0.0078645 ]
 [0.99359   ]
 [0.9921176 ]]


In [37]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [38]:
w = np.array([0.2, 0.3, 0.8])
b = 0.5
x = np.array([0.5, 0.6, 0.1])

In [39]:
print(w)

[0.2 0.3 0.8]


In [40]:
print(b)

0.5


In [41]:
z = w.dot(x) + b
print("z:", z)
print("a:", sigmoid(z))

z: 0.8600000000000001
a: 0.7026606543447316


In [42]:
def activation(z):
    if z > 0:
        return 1
    return 0

In [43]:
w = np.array([1, 1])
b = -1

In [44]:
print(w)

[1 1]


In [45]:
print(b)

-1


In [46]:
x = np.array([0, 0])
print("0 AND 0:", activation(w.dot(x) + b))

0 AND 0: 0


In [47]:
x = np.array([1, 0])
print("1 AND 0:", activation(w.dot(x) + b))
x = np.array([0, 1])
print("0 AND 1:", activation(w.dot(x) + b))
x = np.array([1, 1])
print("1 AND 1:", activation(w.dot(x) + b))

1 AND 0: 0
0 AND 1: 0
1 AND 1: 1
